apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nyctaxi-job-
  namespace: spark
spec:
  serviceAccountName: arcjob
  ttlStrategy:
    # keep workflows for 30m
    secondsAfterCompletion: 1800
  entrypoint: nyctaxi
  templates:
  - name: nyctaxi
    dag:
      tasks:
        - name: step1-query
          templateRef:
            name: spark-template
            template: sparkLocal 
          arguments:
            parameters:
            - name: jobId
              value: nyctaxi 
            - name: tags
              value: "project=sqlbasedetl owner=myowner costcenter=66666" 
            - name: configUri
              value: https://aws-jam-challenge-resources.s3.amazonaws.com/spark-on-eks-made-easy/nyctaxi-job.ipynb
            - name: parameters
              value: "--ETL_CONF_DATA_URL=https://aws-jam-challenge-resources.s3.amazonaws.com/spark-on-eks-made-easy/yellow_tripdata_2021-01.parquet"