apiVersion: v1
kind: Pod
metadata:
  labels:
    spark-role: driver
  namespace: spark
spec:
  serviceAccountName: nativejob
  affinity: 
      nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms:
              - matchExpressions:
                - key: lifecycle 
                  operator: In 
                  values: 
                  - OnDemand
